# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.6.0-dev

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-05-22T22:40:42Z"
  labels:
    app: chris-pod
  name: chris-pod
spec:
  ports:
  - name: "8000"
    nodePort: 30569
    port: 8000
    targetPort: 8000
  selector:
    app: chris-pod
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.podman.annotations.ulimit: nofile=1048576:1048576
  creationTimestamp: "2023-05-22T22:40:42Z"
  labels:
    app: chris-pod
  name: chris-pod
spec:
  containers:
  - args:
    - mod_wsgi-express
    - start-server
    - config/wsgi.py
    - --host
    - 0.0.0.0
    - --port
    - "8000"
    - --processes
    - "4"
    - --limit-request-body
    - "5368709120"
    - --server-root
    - /home/localuser/mod_wsgi-0.0.0.0:8000
    env:
    - name: DJANGO_USE_X_FORWARDED_HOST
      value: "false"
    - name: CELERY_BROKER_URL
      value: amqp://queue:5672
    - name: SWIFT_CONTAINER_NAME
      value: users
    - name: POSTGRES_DB
      value: chris
    - name: AUTH_LDAP
      value: "false"
    - name: DJANGO_SETTINGS_MODULE
      value: config.settings.production
    - name: DATABASE_HOST
      value: chris_db
    - name: SWIFT_USERNAME
      value: chris:chris1234
    - name: CUBE_CELERY_POLL_INTERVAL
      value: "5.0"
    - name: POSTGRES_USER
      value: chris
    - name: STATIC_ROOT
      value: /home/localuser/mod_wsgi-0.0.0.0:8000/htdocs/static/
    - name: DATABASE_PORT
      value: "5432"
    - name: DJANGO_CORS_ALLOWED_ORIGINS
      value: https://babymri.org
    - name: DJANGO_CORS_ALLOW_ALL_ORIGINS
      value: "true"
    - name: CHRIS_STORE_URL
      value: http://chrisstore.local:8010/api/v1/
    - name: SWIFT_KEY
      value: testing
    - name: DJANGO_DB_MIGRATE
      value: "on"
    - name: DJANGO_ALLOWED_HOSTS
      value: '*'
    - name: SWIFT_AUTH_URL
      value: http://swift:8080/auth/v1.0
    - name: DJANGO_COLLECTSTATIC
      value: "on"
    - name: POSTGRES_PASSWORD
      value: chris1234
    - name: DJANGO_SECRET_KEY
      value: secret
    image: ghcr.io/fnndsc/cube:3.0.0.a15
    name: chris
    ports:
    - containerPort: 8000
    securityContext: {}
  - image: docker.io/fnndsc/chrisomatic:0.3.0
    name: chrisomatic
    volumeMounts:
    - mountPath: /chrisomatic.yml
      name: home-rbanda-chrisomatic.yml-host-0
      readOnly: true
    - mountPath: /var/run/docker.sock
      name: var-run-docker.sock-host-1
  volumes:
  - hostPath:
      path: /home/rbanda/chrisomatic.yml
      type: File
    name: home-rbanda-chrisomatic.yml-host-0
  - hostPath:
      path: /var/run/docker.sock
      type: File
    name: var-run-docker.sock-host-1
