---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    app.kubernetes.io/part-of: miniChRIS
  annotations:
    kubernetes.io/description: "Configuration of a PostgresSQL databse used by the ChRIS backend"
data:
  POSTGRES_DB: "chris"
  POSTGRES_USER: "chris"
  POSTGRES_PASSWORD: "chris1234"
