---
- name: Run ChRIS application with ansible-playbook
  hosts: localhost
  vars:
    CUBE_POD: minichris-cube-pod
    HERE: "{{ playbook_dir }}"
    HARD_CODED_SOCK: '/run/user/1000/podman/podman.sock'
    CHRISOMATIC_IMAGE: ghcr.io/fnndsc/chrisomatic:0.4.1

  tasks:
    - name: Create and Enable Podman Socket If Not Present
      block:
        - name: Determine the xdg_runtime_dir             # This is necessary for finding the podman.sock location on the host
          block:
            - name: Get the uid of the current user
              command: "id -u {{ ansible_user_id }}"      # This command returns the user's id number that may usually be 1000
              register: user_id_number
            
            - name: Set the xdg_runtime_dir variable
              set_fact:
                xdg_runtime_dir: "/run/user/{{ user_id_number.stdout }}"
              changed_when: false

        - name: Check if podman socket exists
          ansible.builtin.stat:
            path: "{{ xdg_runtime_dir}}/podman/podman.sock"
          register: podman_socket

        - name: Create podman socket file if not exists
          ansible.builtin.copy:
            content: |
              [Unit]
              Description=Podman API Socket
              Documentation=man:podman-system-service(1)

              [Socket]
              ListenStream=%t/podman/podman.sock
              SocketMode=0660

              [Install]
              WantedBy=sockets.target
            dest: /usr/lib/systemd/user/podman.socket
          when: podman_socket.stat.exists == false

        - name: Enable and start the podman socket
          environment:
            XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
          ansible.builtin.systemd:
            name: podman.socket
            enabled: true
            state: started
            scope: user
            daemon_reload: true
      tags: up


    - name: Start Podman Service
      ansible.builtin.systemd:
        name: podman.service
        state: started
        scope: user
        daemon_reload: true
      tags: up

    - name: Pull All Required Images
      containers.podman.podman_image:
        name: "{{ item }}"
      loop:
      - docker.io/library/postgres:13
      - docker.io/library/rabbitmq:3
      - ghcr.io/fnndsc/cube:4.0.0.pre12
      - ghcr.io/fnndsc/chris_ui:20230523.257-cbc71ea8
      - ghcr.io/fnndsc/pfcon:5.0.0
      - ghcr.io/fnndsc/pman:5.0.0.a5
      - "{{ CHRISOMATIC_IMAGE }}"
      tags: up

    - name: Register The SOCK Variable
      ansible.builtin.command: '{% raw %}podman info --format {{.Host.RemoteSocket.Path}}{% endraw %}'
      register: SOCK
      tags: [ up, chrisomatic ]

    # This is for minichris.sh up
    - name: Start Up ChRIS
      block:
        - name: Start cube
          ansible.builtin.shell: "cat {{ HERE }}/kube/*.yml | podman kube play --replace -"

        - name: Start pfcon
          block:
            - name: Replacing HARD_CODED_SOCK with the SOCK value
              ansible.builtin.replace:
                path: "{{ HERE }}/pfcon-podman.yml"
                regexp: "{{ HARD_CODED_SOCK }}"
                replace: "{{ SOCK.stdout }}"

            - name: Run the pfcon-podman file
              command: "podman kube play --start --replace {{ HERE }}/pfcon-podman.yml"

        - name: Start up Chrisomatic
          block:
            - name: Start chrisomatic
              command: "podman run --name chrisomatic-container --pod {{ CUBE_POD }} --security-opt label=disable -v {{ HERE }}/chrisomatic.yml:/chrisomatic.yml:ro -v {{ SOCK.stdout }}:/var/run/docker.sock:rw {{ CHRISOMATIC_IMAGE }} chrisomatic"
              ignore_errors: true

            - name: Check chrisomatic-container status
              ansible.builtin.command: podman logs chrisomatic-container
              register: container_status
              ignore_errors: true

            - name: Display container status
              ansible.builtin.debug:
                msg: "{{ container_status.stdout_lines}}"
              ignore_errors: true
              when: container_status is success

            - name: End Chrisomatic
              command: podman rm chrisomatic-container
          tags: chrisomatic
      tags: up

    # This is for minichris.sh down
    - name: Stop ChRIS
      ansible.builtin.shell: "cat {{ HERE }}/kube/*.yml {{ HERE }}/pfcon-podman.yml | exec podman kube down --force -"
      tags: down
