---
- name: Run ChRIS application with ansible-playbook
  hosts: localhost
  vars:
    CUBE_POD: minichris-cube-pod
    HERE: "{{ playbook_dir }}"
    HARD_CODED_SOCK: '/run/user/1000/podman/podman.sock'
    CHRISOMATIC_IMAGE: ghcr.io/fnndsc/chrisomatic:0.4.1

  tasks:
    - name: Start podman.service
      ansible.builtin.systemd:
        name: podman.service
        state: started
        scope: user
      tags: up

    - name: Pull all required images
      containers.podman.podman_image:
        name: "{{ item }}"
      loop:
      - docker.io/library/postgres:13
      - docker.io/library/rabbitmq:3
      - ghcr.io/fnndsc/cube:4.0.0.pre12
      - ghcr.io/fnndsc/chris_ui:20230523.257-cbc71ea8
      - ghcr.io/fnndsc/pfcon:5.0.0
      - ghcr.io/fnndsc/pman:5.0.0.a5
      - "{{ CHRISOMATIC_IMAGE }}"
      tags: up

    - name: Register the SOCK variable
      ansible.builtin.command: '{% raw %}podman info --format {{.Host.RemoteSocket.Path}}{% endraw %}'
      register: SOCK
      tags: [ up, chrisomatic ]

    # This is for minichris.sh up
    - name: Start up ChRIS
      block:
        - name: Start cube
          ansible.builtin.shell: "cat {{ HERE }}/kube/*.yml | podman kube play --replace -"

        - name: Start pfcon
          block:
            - name: Replacing HARD_CODED_SOCK with the SOCK value
              ansible.builtin.replace:
                path: "{{ HERE }}/pfcon-podman.yml"
                regexp: "{{ HARD_CODED_SOCK }}"
                replace: "{{ SOCK.stdout }}"

            - name: Run the pfcon-podman file
              command: "podman kube play --start --replace {{ HERE }}/pfcon-podman.yml"

        - name: Start up Chrisomatic
          block:
            - name: Start chrisomatic
              command: "podman run --name chrisomatic-container --pod {{ CUBE_POD }} --security-opt label=disable -v {{ HERE }}/chrisomatic.yml:/chrisomatic.yml:ro -v {{ SOCK.stdout }}:/var/run/docker.sock:rw {{ CHRISOMATIC_IMAGE }} chrisomatic"
              ignore_errors: true

            - name: Check chrisomatic-container status
              ansible.builtin.command: podman logs chrisomatic-container
              register: container_status
              ignore_errors: true

            - name: Display container status
              ansible.builtin.debug:
                msg: "{{ container_status.stdout_lines}}"
              ignore_errors: true
              when: container_status is success

            - name: End Chrisomatic
              command: podman rm chrisomatic-container
          tags: chrisomatic
      tags: up

    # This is for minichris.sh down
    - name: Stop ChRIS
      ansible.builtin.shell: "cat {{ HERE }}/kube/*.yml {{ HERE }}/pfcon-podman.yml | exec podman kube down --force -"
      tags: down
