name: Ansible Playbook

on:
  push:
    branches:
      - main  # Adjust this to your default branch if it's not "main"

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible playbook
        uses: softprops/action-ansible@v1
        with:
          playbook: ChRIS-in-a-box/podman/chri_play.yml
          inventory: localhost,
          extra_vars: '{"arg": "up"}'
