
name: Ansible Playbook to deploy chris using Podman

on:
  push:
    branches:
      - main  # Adjust this to your default branch if it's not "main"

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible playbook
        working-directory: ChRIS-in-a-box/podman/
        run: |
          ansible-playbook chri_play.yml -e arg="up"
