name: Ansible Pipeline

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the pipeline on

jobs:
  ansible_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get -y install ansible

      - name: Run Ansible playbook
        run: ansible-playbook ./podman/chris_play.yml -e arg="up"
