name: ChRIS-in-a-box Playbook

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the pipeline on

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use the appropriate Python version for your playbook

      - name: Install Ansible
        run: pip install ansible

      - name: Run ChRIS-in-a-box Playbook
        working-directory: podman  # Change this if the playbook is in a different path
        run: ansible-playbook minichris.yml --extra-vars "arg=up"
