name: Install Dependencies and Build Go
on:
  push:
    branches:
      - quad
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            btrfs-progs \
            crun \
            git \
            golang-go \
            go-md2man \
            iptables \
            libassuan-dev \
            libbtrfs-dev \
            libc6-dev \
            libdevmapper-dev \
            libglib2.0-dev \
            libgpgme-dev \
            libgpg-error-dev \
            libprotobuf-dev \
            libprotobuf-c-dev \
            libseccomp-dev \
            libselinux1-dev \
            libsystemd-dev \
            pkg-config \
            build-essential\
            libsystemd-dev\
            uidmap
            
      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
          # Specify any additional Go versions you need

      - name: Set GOPATH
        run: |
          echo "export GOPATH=~/go" >> $GITHUB_ENV

      - name: Update PATH
        run: |
          echo "export PATH=\$GOPATH/bin:\$PATH" >> $GITHUB_ENV
    
      - name: Install Make
        run: sudo apt-get install make
      
      - uses: actions/checkout@v2
        with:
          repository: containers/conmon
   
      - name: list files
        run: ls -lart

      - name: Set up GOCACHE
        run: export GOCACHE="$(mktemp -d)"

      - name: Build Conmon
        run: make

      - name: Install Podman
        run: sudo make podman
     
      - name: Check runc
        run: runc --version
        
      - name: Create /etc/containers directory
        run: sudo mkdir -p /etc/containers

      - name: Download registries.conf
        run: sudo curl -L -o /etc/containers/registries.conf https://src.fedoraproject.org/rpms/containers-common/raw/main/f/registries.conf

      - name: Download policy.json
        run: sudo curl -L -o /etc/containers/policy.json https://src.fedoraproject.org/rpms/containers-common/raw/main/f/default-policy.json
      
      - name: Clone Podman Repository
        run: git clone https://github.com/containers/podman/

      - name: List Repository Contents After Clone
        run: ls -la

      - name: Build and Install Podman
        run: |
          cd podman
          make BUILDTAGS="selinux seccomp"
          sudo make install PREFIX=/usr
