name: Install Packages

on:
  push:
    branches:
      - quad

jobs:
  install-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            btrfs-progs \
            crun \
            git \
            golang-go \
            go-md2man \
            iptables \
            libassuan-dev \
            libbtrfs-dev \
            libc6-dev \
            libdevmapper-dev \
            libglib2.0-dev \
            libgpgme-dev \
            libgpg-error-dev \
            libprotobuf-dev \
            libprotobuf-c-dev \
            libseccomp-dev \
            libselinux1-dev \
            libsystemd-dev \
            pkg-config \
            uidmap
