name: Install Packages

on:
  push:
    branches:
      - quad

jobs:
  install-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            btrfs-progs \
            crun \
            git \
            golang-go \
            go-md2man \
            iptables \
            libassuan-dev \
            libbtrfs-dev \
            libc6-dev \
            libdevmapper-dev \
            libglib2.0-dev \
            libgpgme-dev \
            libgpg-error-dev \
            libprotobuf-dev \
            libprotobuf-c-dev \
            libseccomp-dev \
            libselinux1-dev \
            libsystemd-dev \
            pkg-config \
            uidmap
      - name: Set GOPATH
        run: export GOPATH=~/go
      
      - name: Clone Go repository
        run: git clone https://go.googlesource.com/go $GOPATH
      
      - name: Change directory to Go source
        run: cd $GOPATH/src
      
      - name: Build and test
        run: ./all.bash
      
      - name: Add Go binaries to PATH
        run: export PATH=$GOPATH/bin:$PATH
