name: Install Dependencies and Build Go
on:
  push:
    branches:
      - quad
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remove existing Podman
        run: |
          sudo apt-get remove -y podman
          sudo apt-get autoremove -y
          sudo rm -rf /etc/containers /var/lib/containers /var/lib/podman
        
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            btrfs-progs \
            crun \
            git \
            golang-go \
            go-md2man \
            iptables \
            libassuan-dev \
            libbtrfs-dev \
            libc6-dev \
            libdevmapper-dev \
            libglib2.0-dev \
            libgpgme-dev \
            libgpg-error-dev \
            libprotobuf-dev \
            libprotobuf-c-dev \
            libseccomp-dev \
            libselinux1-dev \
            libsystemd-dev \
            pkg-config \
            build-essential\
            libsystemd-dev\
            uidmap
            
      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
          # Specify any additional Go versions you need

      - name: Set GOPATH
        run: |
          echo "export GOPATH=~/go" >> $GITHUB_ENV

      - name: Update PATH
        run: |
          echo "export PATH=\$GOPATH/bin:\$PATH" >> $GITHUB_ENV
    
      - name: Install Make
        run: sudo apt-get install make
      
      - uses: actions/checkout@v2
        with:
          repository: containers/conmon

      - name: Set up GOCACHE
        run: export GOCACHE="$(mktemp -d)"

      - name: Build Conmon
        run: make

      - name: Install Podman
        run: sudo make podman
     
      - name: Check runc
        run: runc --version
        
      - name: Create /etc/containers directory
        run: sudo mkdir -p /etc/containers

      - name: Download registries.conf
        run: sudo curl -L -o /etc/containers/registries.conf https://src.fedoraproject.org/rpms/containers-common/raw/main/f/registries.conf

      - name: Download policy.json
        run: sudo curl -L -o /etc/containers/policy.json https://src.fedoraproject.org/rpms/containers-common/raw/main/f/default-policy.json
    
      - name: Cleanup existing Podman directory
        run: rm -rf podman/
    
      - name: Clone Podman Repository
        run: |
          git clone https://github.com/containers/podman/
          cd podman
          git pull origin main
          
      - name: Set Go version to 1.17
        run: cd podman && go mod edit -go=1.17
        
      - name: Upgrade versions for Go 1.16 compatibility
        run: cd podman && go mod tidy -go=1.16 && go mod tidy -go=1.17
      - name: Sync Vendor Directory
        run: cd podman && go mod vendor
        
      - name: Cleanup 
        run: rm -rf podman/vendor/github.com/containers/image
        
      - name: Build and Install Podman
        run: |
          cd podman
          go mod tidy
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build \
            -ldflags '-X github.com/containers/podman/v4/libpod/define.gitCommit=47ac6c4cbe1fea2f78b1f72937b43a8c6be28420-dirty -X github.com/containers/podman/v4/libpod/define.buildInfo=1684962577 -X github.com/containers/podman/v4/libpod/config._installPrefix=/usr/local -X github.com/containers/podman/v4/libpod/config._etcDir=/etc -X github.com/containers/podman/v4/pkg/systemd/quadlet._binDir=/usr/local/bin -X github.com/containers/common/pkg/config.additionalHelperBinariesDir= ' \
           -tags "selinux seccomp systemd" \
          -o bin/podman ./cmd/podman
          sudo make install PREFIX=/usr
          


