name: Install Dependencies and Build Go
on:
  push:
    branches:
      - quad
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            btrfs-progs \
            crun \
            git \
            golang-go \
            go-md2man \
            iptables \
            libassuan-dev \
            libbtrfs-dev \
            libc6-dev \
            libdevmapper-dev \
            libglib2.0-dev \
            libgpgme-dev \
            libgpg-error-dev \
            libprotobuf-dev \
            libprotobuf-c-dev \
            libseccomp-dev \
            libselinux1-dev \
            libsystemd-dev \
            pkg-config \
            uidmap
            
      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
          # Specify any additional Go versions you need

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set GOPATH
        run: |
          echo "export GOPATH=~/go" >> $GITHUB_ENV

      - name: Clone Go repository
        run: |
          rm -rf /home/runner/go
          git clone https://go.googlesource.com/go $HOME/go

      - name: Build Go
        run: |
          cd $HOME/go/src
          ./all.bash

      - name: Update PATH
        run: |
          echo "export PATH=\$GOPATH/bin:\$PATH" >> $GITHUB_ENV
