name: Go Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
          # Specify any additional Go versions you need

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set GOPATH
        run: |
          echo "export GOPATH=~/go" >> $GITHUB_ENV

      - name: Clone Go repository
        run: |
          git clone https://go.googlesource.com/go $HOME/go

      - name: Build Go
        run: |
          cd $HOME/go/src
          ./all.bash

      - name: Update PATH
        run: |
          echo "export PATH=\$GOPATH/bin:\$PATH" >> $GITHUB_ENV
